#!/bin/bash -e

./mkgen 3
time ./reg gen/*/games
time ./match match.history
time ./selflearn 500

./mkgen 4
time ./reg gen/*/games
time ./match match.history
time ./selflearn 500

./mkgen 5
time ./reg gen/*/games
time ./match match.history
time ./selflearn 1000

./mkgen 6
time ./reg gen/*/games
time ./match match.history
time ./selflearn 1000

./mkgen 7
time ./reg gen/*/games
time ./match match.history
time ./selflearn 2000

./mkgen 8
time ./reg gen/*/games
time ./match match.history
time ./selflearn 2000
