#!/bin/bash -e

for i in $(seq 0 9); do
    L2=$(cat L2/$i 2>/dev/null || true)
    if [ "$L2" ]; then
        L2ARG="--l2=$L2"
        echo "Using $L2ARG"
    elif [ "$DEFAULT_L2" ]; then
        L2ARG="--l2=$DEFAULT_L2"
        echo "Using $L2ARG"
    fi
    npx coffee --nodejs --max-old-space-size=4096 minibatch -p $i -o tmp/coeffs$i $L2ARG $@
done
cp -p weights.json weights.json.bak
npx coffee coeffs_to_weights
