#!/bin/bash -e

if [ ! "$1" ]; then
    echo "Usage: $0 games"
    exit 1
fi

cat "$@" | ./games_to_minmax_nodes - tmp/nodes.gz
./nodes_to_single_indexes tmp/nodes.gz
for i in $(seq 0 9); do
    ./regress tmp/indexes$i.gz tmp/coeffs$i
done
./coeffs_to_score
