#!/bin/bash -e

if [ ! "$1" ]; then
    echo "Usage: $0 games"
    exit 1
fi

./balancer $@ | ./games_to_nodes - | ./nodes_to_single_indexes -
for i in $(seq 0 9); do
    ./regress tmp/indexes$i.gz tmp/coeffs$i
done
./coeffs_to_score
