#!/bin/bash -e

if [ ! "$1" ]; then
    echo "Usage: $0 games"
    exit 1
fi

./split_games "$@"
./games_to_minmax_nodes tmp/train_games.gz tmp/train_nodes.gz
./games_to_minmax_nodes tmp/test_games.gz tmp/test_nodes.gz
./nodes_to_single_indexes train
./nodes_to_single_indexes test
for i in $(seq 0 9); do
    ./regress tmp/train_indexes$i.gz tmp/test_indexes$i.gz tmp/coeffs$i
done
./coeffs_to_score
