#!/bin/bash -e
while true; do
    time ./selfplay-bf -n 200
    time ./selfplay-rnd --opening f5 -n 200
    time ./selfplay-rnd --opening f5d6 -n 200
    time ./selfplay-rnd --opening f5f6 -n 200
    time ./selfplay-rnd --opening f5f4 -n 200
    time ./reg -t 1e-3
    time ./match match.log
done
