#!/bin/bash -e
while true ; do
    # Play until scores.json is updated
    if [ match.log -nt scores.json ]; then
        npx coffee selfplay-rnd -av
    fi

    d=snapshots/$(date +%Y-%m-%d_%H:%M:%S)
    mkdir -p $d
    sqlite3 book.db 'select count(*) from games' >$d/count
    cp -p scores.json $d
    gzip $d/scores.json

    time npx coffee match match.log

    cp -p match.log $d
done
