#!/bin/bash

while true; do
    if [ weights.json -nt .stamp-weights ]; then
        ls -l weights.json
        if type jq >/dev/null 2>&1; then
            jq .meta[].r2 weights.json
        fi
        touch .stamp-weights
    fi
    if [ match.log -nt .stamp-match ]; then
        tail -n 1 match.log
        touch .stamp-match
    fi
    echo $(sqlite3 book.db '
        select max(c) from (select count(*) c from game_nodes group by n_moves);
        select sum(outcome) from game_nodes;')
    sleep 60 
done
